"""Evolve applier — closes the format-evolution self-improvement loop, PR-gated.

`evolve_format()` files a suggestion to improve thread-keeper's brief format (the
session-start memory snapshot rendered by `render_brief` in `brief.py`). The
`evolve_reviewer` daemon PROMOTES the good ones — and the brief surfaces them
with a ★. Until now that's where it stopped: a human had to hand-edit `brief.py`.

This module automates the IMPLEMENTATION, with a pull request as the human gate:

  apply_evolve(evolve_id)  — look up a PROMOTED + not-applied suggestion, build
  an implementer prompt, and spawn() an `evolve_applier` child that EDITS
  `brief.py` (`render_brief`), adds/extends a GOLDEN render_brief test, runs the
  FULL suite, and opens a PR on a feature branch. The child NEVER pushes or
  commits to main (main has branch protection); a human reviews + merges.

On a successful `gh pr create`, the child calls
`evolve_mark_applied(evolve_id, pr_url)` → `applied=1`, so the suggestion stops
resurfacing in the brief / `evolve_review`.

The optional daemon (`THREADKEEPER_EVOLVE_APPLY_INTERVAL_S > 0`, default 0 = off)
periodically picks the oldest promoted+unapplied suggestion and fires
apply_evolve for it. Mirror of evolve_daemon / candidate_reviewer: foreground-
only, machine-wide single-flight via the prompt prefix, child runs with
`write_origin='evolve_apply'` so it can't recursively start daemons.

The objective gate the loop has lacked: the child must make a golden
render_brief test pass AND keep the full suite green before it may open the PR.
"""

from __future__ import annotations

import logging
import re
import sqlite3
import threading
import time
from pathlib import Path
from typing import Optional

from .config import EVOLVE_APPLY_INTERVAL_S
from .db import get_db
from . import identity

logger = logging.getLogger(__name__)

_started = False

# First line of the implementer child's prompt. Added to
# shadow_review._INTERNAL_PROMPT_PREFIXES so the child's transcript (it edits
# code + runs gh) doesn't pollute extract/shadow learning windows on re-ingest.
EVOLVE_APPLY_PROMPT_PREFIX = "You are an EVOLVE APPLIER"

EVOLVE_APPLY_PROMPT = """\
You are an EVOLVE APPLIER for thread-keeper. A past session filed a suggestion
to improve thread-keeper's OWN brief format — the session-start memory snapshot
rendered by render_brief() in threadkeeper/brief.py. The evolve reviewer
PROMOTED it. Your job: IMPLEMENT it in code, VALIDATE with the test suite, and
open a PULL REQUEST. A human reviews and merges — you NEVER merge or touch main.

SUGGESTION #{evolve_id}
=======================
{suggestion}
{rationale_block}
REPO: {repo}   (run everything from here; the project venv is .venv/)

DO, strictly in order:

1. READ threadkeeper/brief.py — specifically render_brief() — and understand the
   sections it emits (core_memory, style, verbatim, open/idle/closed threads,
   evolve_pending, the trailing user-facing reminder, ...). Find exactly where
   the suggestion applies.

2. IMPLEMENT the suggestion by editing render_brief() (and only the helper(s) it
   needs). Keep the change surgical and in the existing house style — match the
   surrounding section idiom. Do NOT reformat or touch unrelated code.

3. ADD or EXTEND A GOLDEN TEST under tests/ (extend tests/test_brief_sections.py
   or add tests/test_evolve_apply_{evolve_id}.py). It MUST assert BOTH:
     (a) the NEW behavior/field the suggestion asks for actually appears in the
         rendered brief for a seeded fixture, AND
     (b) the EXISTING brief still renders — assert a couple of pre-existing
         sections (e.g. a seeded open thread, the evolve_pending ★, the
         user-facing reminder) are STILL present. A format change must not
         silently break the brief.
   Mirror the bootstrap/fixture style of tests/test_brief_sections.py and
   tests/test_evolve_daemon.py (env setup, module reload, render_brief(conn)).

4. RUN THE FULL SUITE from the repo root and read the FINAL summary line:
       .venv/bin/python -m pytest -q
   It MUST report 0 failed (e.g. "=== N passed in Xs ==="). If anything fails,
   FIX it (your change or your test) and re-run until green. Do NOT proceed
   while red.

5. OPEN A PR — only after the suite is GREEN:
     • Create a NEW feature branch (NEVER commit on main):
         git checkout -b {branch}
     • Stage ONLY the files you changed, commit with a clear message, push:
         git add threadkeeper/brief.py tests/<your_test_file>
         git commit -m "evolve: <short imperative summary>"
         git push -u origin {branch}
     • Open the PR; the body MUST quote the suggestion text + rationale and note
       it was generated by evolve_applier:
         gh pr create --title "evolve: <short>" --body "<body incl. suggestion + rationale>"
     • Capture the PR URL that gh prints.

6. RECORD COMPLETION — ONLY after gh pr create printed a real PR URL — call the
   thread-keeper MCP tool:
       evolve_mark_applied(evolve_id={evolve_id}, pr_url="<the PR url>")
   This sets applied=1 so the suggestion stops resurfacing.

HARD CONSTRAINTS (non-negotiable):
  • NEVER commit, push, or force-push to main. main has branch protection.
  • NEVER merge the PR — a human does that.
  • If you CANNOT make the full suite green, do NOT open a PR and do NOT call
    evolve_mark_applied. Broadcast a one-line failure summary and stop.
  • When you report, paraphrase in plain language; don't cite internal IDs.

When finished, output exactly ONE final line:
  EVOLVE_APPLY_COMPLETE pr=<url>      (success), or
  EVOLVE_APPLY_ABORTED reason=<why>   (could not complete safely).
"""


def _repo_root() -> Path:
    """Repository root = the package's parent dir (threadkeeper/.. )."""
    return Path(__file__).resolve().parent.parent


def _slug(text: str, maxlen: int = 32) -> str:
    """kebab-case slug for a branch name; alnum+dash only, lowercased."""
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    s = s[:maxlen].rstrip("-")
    return s or "change"


def branch_name(evolve_id: int, suggestion: str) -> str:
    return f"evolve/apply-{int(evolve_id)}-{_slug(suggestion)}"


def build_apply_prompt(evolve_id: int, suggestion: str,
                       rationale: Optional[str],
                       repo_root: Optional[Path] = None) -> str:
    """Render the implementer child's prompt for one suggestion."""
    repo = str(repo_root or _repo_root())
    rationale_block = (
        f"RATIONALE: {rationale}\n" if (rationale or "").strip() else ""
    )
    return EVOLVE_APPLY_PROMPT.format(
        evolve_id=int(evolve_id),
        suggestion=suggestion,
        rationale_block=rationale_block,
        repo=repo,
        branch=branch_name(evolve_id, suggestion),
    )


def _get_promoted_unapplied(conn: sqlite3.Connection,
                            evolve_id: int) -> Optional[sqlite3.Row]:
    """Fetch a single evolve row IF it is promoted and not yet applied."""
    try:
        return conn.execute(
            "SELECT id, suggestion, rationale FROM evolve "
            "WHERE id=? AND applied=0 "
            "AND COALESCE(status,'pending')='promoted'",
            (int(evolve_id),),
        ).fetchone()
    except sqlite3.OperationalError:
        return None


def _promoted_unapplied(conn: sqlite3.Connection) -> list[sqlite3.Row]:
    """All promoted+unapplied suggestions, oldest first (FIFO drain order)."""
    try:
        return conn.execute(
            "SELECT id, suggestion, rationale FROM evolve "
            "WHERE applied=0 AND COALESCE(status,'pending')='promoted' "
            "ORDER BY created_at ASC, id ASC"
        ).fetchall()
    except sqlite3.OperationalError:
        return []


def _row_exists(conn: sqlite3.Connection, evolve_id: int) -> bool:
    return conn.execute(
        "SELECT 1 FROM evolve WHERE id=?", (int(evolve_id),)
    ).fetchone() is not None


def _running_applier_children(conn: sqlite3.Connection) -> list[str]:
    """Running applier task ids, reaping dead rows. Machine-wide single-flight:
    one applier child at a time across all servers (two would both edit
    brief.py and collide on the branch)."""
    from .helpers import alive
    try:
        rows = conn.execute(
            "SELECT id, pid FROM tasks WHERE ended_at IS NULL "
            "AND prompt LIKE ?",
            (EVOLVE_APPLY_PROMPT_PREFIX + "%",),
        ).fetchall()
    except sqlite3.OperationalError:
        return []
    now = int(time.time())
    running: list[str] = []
    touched = False
    for r in rows:
        pid = int(r["pid"] or 0)
        if pid > 0 and not alive(pid):
            conn.execute(
                "UPDATE tasks SET ended_at=? WHERE id=? AND ended_at IS NULL",
                (now, r["id"]),
            )
            touched = True
            continue
        running.append(r["id"])
    if touched:
        conn.commit()
    return running


def mark_applied(conn: sqlite3.Connection, evolve_id: int,
                 pr_url: str) -> str:
    """Set applied=1 for an evolve row and record the PR. The PR-gate: this is
    only ever reached once a real PR exists (the child calls it after
    `gh pr create`). Returns a status string."""
    if not _row_exists(conn, evolve_id):
        return f"ERR evolve_not_found={evolve_id}"
    conn.execute(
        "UPDATE evolve SET applied=1 WHERE id=?", (int(evolve_id),)
    )
    try:
        conn.execute(
            "INSERT INTO events (session_id, kind, target, summary, created_at) "
            "VALUES (?, 'evolve_applied', ?, ?, ?)",
            (identity._session_id or "", str(int(evolve_id)),
             (pr_url or "")[:300], int(time.time())),
        )
    except sqlite3.OperationalError:
        pass
    conn.commit()
    return f"ok id={evolve_id} applied=1 pr={pr_url}"


def apply_evolve(evolve_id: int) -> str:
    """Spawn an `evolve_applier` child to IMPLEMENT a promoted suggestion and
    open a PR. The manual entry point (always available — does NOT depend on the
    daemon interval). Does NOT set applied=1; that happens only when the child
    reports a real PR via evolve_mark_applied → mark_applied().

    Status strings:
      'ERR evolve_not_found=<id>'      — no such row
      'ERR not_actionable=<id> …'      — exists but not promoted+unapplied
      'applier_running n=<k>'          — an applier child is already in flight
      'spawned evolve_id=<id> …'       — launched the implementer child
      'spawn_error: …'                 — spawn rejected
    """
    conn = get_db()
    if not _row_exists(conn, evolve_id):
        return f"ERR evolve_not_found={evolve_id}"
    row = _get_promoted_unapplied(conn, evolve_id)
    if not row:
        cur = conn.execute(
            "SELECT applied, COALESCE(status,'pending') AS st FROM evolve "
            "WHERE id=?", (int(evolve_id),),
        ).fetchone()
        return (
            f"ERR not_actionable={evolve_id} applied={cur['applied']} "
            f"status={cur['st']} (need promoted + applied=0)"
        )

    running = _running_applier_children(conn)
    if running:
        return f"applier_running n={len(running)} (single-flight)"

    repo_root = _repo_root()
    prompt = build_apply_prompt(
        row["id"], row["suggestion"], row["rationale"], repo_root
    )

    from .tools.spawn import spawn  # late import — avoids import cycle
    try:
        result = spawn(
            prompt=prompt,
            cwd=str(repo_root),
            visible=False,
            capture_output=True,
            permission_mode="bypassPermissions",
            role="evolve_applier",
            write_origin="evolve_apply",
            slim=True,
            extra_allowed_tools=(
                "Bash,Edit,Write,Read,Glob,Grep,"
                "mcp__thread-keeper__evolve_mark_applied,"
                "mcp__thread-keeper__evolve_review,"
                "mcp__thread-keeper__broadcast"
            ),
        )
    except Exception as e:  # noqa: BLE001 — never crash the daemon/tool
        return f"spawn_error: {e}"
    return f"spawned evolve_id={evolve_id} {str(result)[:140]}"


# ── Optional daemon ───────────────────────────────────────────────────────────


def _last_apply_ts(conn: sqlite3.Connection) -> int:
    """High-water timestamp of the most recent apply pass, or 0."""
    try:
        row = conn.execute(
            "SELECT target FROM events WHERE kind='evolve_apply_pass' "
            "ORDER BY id DESC LIMIT 1"
        ).fetchone()
    except sqlite3.OperationalError:
        return 0
    if not row or not row["target"]:
        return 0
    try:
        return int(row["target"])
    except (ValueError, TypeError):
        return 0


def _record_apply_pass(conn: sqlite3.Connection, ts: int,
                       outcome: str) -> None:
    try:
        conn.execute(
            "INSERT INTO events (session_id, kind, target, summary, "
            "created_at) VALUES (?, 'evolve_apply_pass', ?, ?, ?)",
            (identity._session_id or "", str(ts), outcome[:300],
             int(time.time())),
        )
        conn.commit()
    except sqlite3.OperationalError:
        logger.debug("evolve_applier: failed to record pass", exc_info=True)


def run_evolve_apply_pass(force: bool = False) -> str:
    """One apply pass: pick the oldest promoted+unapplied suggestion and fire
    apply_evolve for it.

    Status strings:
      'disabled'                  — knob off and not forced
      'no_promoted'               — nothing promoted+unapplied to implement
      'applier_running n=<k>'     — an applier child is already in flight
      'spawned evolve_id=<id> …'  — launched the implementer child
      (or any apply_evolve error string)
    """
    if EVOLVE_APPLY_INTERVAL_S <= 0 and not force:
        return "disabled"
    conn = get_db()
    now_t = int(time.time())
    pending = _promoted_unapplied(conn)
    if not pending:
        _record_apply_pass(conn, now_t, "no_promoted")
        return "no_promoted"

    running = _running_applier_children(conn)
    if running:
        out = f"applier_running n={len(running)}"
        _record_apply_pass(conn, now_t, out)
        return out

    top = pending[0]
    out = apply_evolve(top["id"])
    _record_apply_pass(conn, now_t, f"id={top['id']} {out}")
    return out


def _serve_loop() -> None:
    while True:
        try:
            run_evolve_apply_pass()
        except Exception:
            logger.debug("evolve_applier tick failed", exc_info=True)
        time.sleep(EVOLVE_APPLY_INTERVAL_S)


def start_evolve_applier_daemon() -> None:
    """Idempotent starter. No-op when EVOLVE_APPLY_INTERVAL_S<=0. Spawned
    children / non-foreground origins refuse to start it so spawn() can't
    recurse (same cascade prevention as the other daemons)."""
    global _started
    if _started:
        return
    if EVOLVE_APPLY_INTERVAL_S <= 0:
        return
    from .config import BACKGROUND_DAEMONS_ALLOWED
    if not BACKGROUND_DAEMONS_ALLOWED:
        return
    t = threading.Thread(
        target=_serve_loop, name="evolve_applier_daemon", daemon=True,
    )
    t.start()
    _started = True
